### ISSUE TITLE
build without Hunter

### ISSUE THREAD

**Issue by elitak** [filecoin-project/cpp-filecoin#230]
I'm trying to package this for NixOS. I can provide every dependency manually. Can I have some quick tips on how to excise Hunter and let cmake find all the dependencies?

Incidentally, Nix or NixOS probably solves the exact set of problems Hunter is being used for, as far as I can tell. You may want to look into using it; it can similarly install and use a version-pinned build environment on any Linux distro.

**Comment by igor-egorov** [comment]
Hi. Currently, the project's CMake is not ready to exclude Hunter. Btw there was an attempt to do so - please take a look at #114 - there are commits that substitute hunterized dependencies.

An improvement like this is not our primary focus at the moment, but we would be happy to help and see your pull request :)
