### ISSUE TITLE
CMake error: Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by Johnny-Martin** [filecoin-project/cpp-filecoin#31]
OS: WSL(Ubuntu 16.04)
GCC: 7.4
CMake: 3.16.1

Operations:
1, Clone cpp-filecoin Repo and update submodule
2, Set GITHUB_HUNTER_TOKEN and GITHUB_HUNTER_USERNAME in cmake/Hunter/init.cmake file
3, mkdir build && cd build && cmake -DCLANG_TIDY=ON ..

Expected: Configuring successfully.
Result: Configuring incomplete, errors occurred!

Log:
[CMakeOutput.log](https://github.com/filecoin-project/cpp-filecoin/files/3971346/CMakeOutput.log)

[CMakeError.log](https://github.com/filecoin-project/cpp-filecoin/files/3971342/CMakeError.log)

**Comment by igor-egorov** [comment]
Hi @Johnny-Martin,

Unfortunately, CMake of this project has a hard-coded Hunter Binary Cache repository address, which now can be used only by Soramitsu workers.

Sorry for that inconvenience! Please try without specifying GITHUB_HUNTER_TOKEN and GITHUB_HUNTER_USERNAME variables - it should work.
