### ISSUE TITLE
How is the progress of Fuhon project?  I can't find the executable file for mining so called miner_main after build

### ISSUE THREAD

**Issue by Johnny-Martin** [filecoin-project/cpp-filecoin#421]
Hello guys,  I'm so exciting that Filecoin protocol has a C++17 implementation. And I have pay close attention to Fuhon project for a while, but a few things confuse me:
1, How is the progress of Fuhon project?  Is there a schedule for this project？
2, I can't find the executable file for mining so called miner_main after build, what shoud I do if I want debug the behavior of the miner(like interactive with Venus node)？
3, Is there any documents or guidelines for contribute code to ​this project？
4, It will trigger error if I use -CLANG_TIDY=ON option on master branch, and what' the plan for this problem?

**Comment by zuiris** [comment]
Hi @Johnny-Martin, we are also quite excited about Fuhon :)
1. Sure it does, Fuhon node development has been mostly finished.
2. Miner executable: $BUILD_DIR/core/miner/main/miner_main .
$BUILD_DIR: either "-B" flag when running "cmake -B $BUILD_DIR ...", or working dir when running "cmake ..." (without "-B" flag).
3. Not strict guidelines as of now, we can search for "good first issue" items if you want to, guideline is planned to be prepared a little bit later
4. Try building without "-D CLANG_TIDY=ON" (or disable with "-D CLANG_TIDY=OFF").
if you need this flag, check you have "clang-tidy" binary installed and present in PATH, and provide error logs if any.

**Comment by Johnny-Martin** [comment]
Hi zuiris, Thanks for your reply, Today I update the master branch and unfortunately the build failed ：
1, mkdir build && cd build 
2, cmake ..
3, make  -j
<img width="1169" alt="Xnip2021-07-27_15-24-27" src="https://user-images.githubusercontent.com/13740871/127113456-d781ecbb-56da-4d78-88e8-795205b2d4f3.png">

**Comment by ortyomka** [comment]
Hello @Johnny-Martin

Did you update GitHub submodules after updating master branch?
If not, please try this: `git submodule update --init --recursive`

**Comment by Johnny-Martin** [comment]
Hi ortyomka,I had update the submodules before build the project. I think there's something wrong with "our-filecoin-ffi "module, it's not a git submodule but placed in deps folder, it seems the "libfilcrypto.lib" in "out-filecoin-ffi/lib"  folder is not up to date, should I build the "our-filecoin-ffi" manually?

**Comment by ortyomka** [comment]
> should I build the "our-filecoin-ffi" manually?

I think, it should solve problem.

"our-filecoin-ffi" depends on "filecoin-ffi". It is updated when "filecoin-ffi" changes.

**Comment by Johnny-Martin** [comment]
Problem solved, and the miner_main was generated in "build/core/miner/main" folder, just as @zuiris said. 
Thank you guys :)

**Comment by ortyomka** [comment]
Great!
