### ISSUE TITLE
Snapdeals

### ISSUE THREAD

**Issue by Alexey-N-Chernyshov** [filecoin-project/cpp-filecoin#551]
Find information, decompose, create tasks.
Links:
- [Lotus search on snapdeals](https://github.com/filecoin-project/lotus/search?q=snapdeals&type=issues)
- [Zenhub project](https://github.com/orgs/filecoin-project/projects/17#card-70916032)

[FIP-0019](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0019.md)

Glossary:
- CC sector (Committed Capacity) - [sector with no data](https://spec.filecoin.io/systems/filecoin_mining/sector/adding_storage/).

**Comment by Alexey-N-Chernyshov** [comment]
[Tests and definition of done](https://github.com/filecoin-project/lotus/issues/7519):
- Happy path -- successful snap deals update for a variety of different configurations
- Handling of errors from chain, market, sector-storage interactions to the extent these are possible to induce
- Graceful handling of operator error: for example test that marking a deal-laden sectors as snap deals fails early, test what insufficient funds cases look like, exercise deals that live longer than remaining sector lifetime
- Marking for snap deals while sealing deals into another sector has the intended effects, i.e. snap deals prioritized

**Comment by Alexey-N-Chernyshov** [comment]
[Filecoin FFI snapdeal proofs](https://github.com/filecoin-project/lotus/issues/7516) `introduces an endpoint to proofs that does the snap deals replica update and returns a proof that it was done correctly `

**Comment by Alexey-N-Chernyshov** [comment]
[Change miner FSM](https://github.com/filecoin-project/lotus/issues/7515)

1) marked for snap deals 
2) data added 
3) sector-storage system performs update, proof and returns proof data 
4) communication with the chain 
5) cleanup of old sector data

**Comment by Alexey-N-Chernyshov** [comment]
[Sector-storage support](https://github.com/filecoin-project/lotus/issues/7525)
It requires integrating the FFI, adding filetypes, storage manager, scheduler and worker support for doing these ffi operations and storing relevant files and presenting an interface for the FSM

**Comment by Alexey-N-Chernyshov** [comment]
Actors V7 states and migration.
Changes in miner actor state:
- new field in sector
- new field in deadline

**Comment by Alexey-N-Chernyshov** [comment]
TODO:
- actors v7 states
- node api - ExtendedSectorInfo
- miner api - new methods
- miner fsm - new states and transitions
- miner manager - add schedule task type UpdateReplica, more tasks?
- worker - new type UpdateReplica task, more tasks?
- verify - pieceIO, ??? - snap deal verify

**Comment by zuiris** [comment]
FFI (done) <- Worker (UpdateReplica), Verify pieceIO <- Miner Manager (UpdateReplica) <- Miner FSM 
VM update (done) <- Miner FSM
Miner API <- CLI, remote workers (?)
